enableInlineBuilds: true
enableTelemetry: false

httpRetry: 5
httpTimeout: 180000
networkConcurrency: 8

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.5.1.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v2"

# uncomment and update proxy settings if running behind any proxies

# httpProxy: ""
# httpsProxy: ""

# networkSettings:
#   "":
#     httpProxy: ""
#     httpsProxy: ""


# npmRegistryServer: ""

# unsafeHttpWhitelist:
#   - example.com
